name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: thewakingsands/search-proxy
        username: ${{ secrets.THE_DOCKER_USERNAME }}
        password: ${{ secrets.THE_DOCKER_PASSWORD }}
        registry: ${{ secrets.THE_DOCKER_REGISTRY }}
